#!/usr/bin/env bash
#
# Fresh-machine bootstrap: pick a code-signing identity and generate the
# Xcode project.
#
#   scripts/bootstrap.sh                  # write local/signing.xcconfig + xcodegen generate
#   scripts/bootstrap.sh --skip-generate  # only (re)write local/signing.xcconfig
#
# Identity resolution (also honored by scripts/package.sh):
#   1. MIMIDASU_SIGN_IDENTITY env override (verbatim, e.g. "-" for ad-hoc)
#   2. the "Mimidasu Dev" certificate, when present in the keychain — keeps TCC
#      grants (Screen Recording) stable across rebuilds
#   3. ad-hoc signing ("-") — builds everywhere; macOS re-asks for Screen
#      Recording access after each rebuild
#
# local/signing.xcconfig is gitignored and is the sole source of
# CODE_SIGN_IDENTITY (project.yml does not set it, so the xcconfig wins).
# This script must run before every `xcodegen generate` on a new machine —
# the generated project cannot resolve its signing config without the file.
#
# Prereqs: xcode-select --install; brew install xcodegen
#          (cmake + ninja for scripts/build_runtime.sh,
#           rustup/cargo for scripts/build_tokenizer.sh)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
XCCONFIG="${REPO_ROOT}/local/signing.xcconfig"
PREFERRED_IDENTITY="Mimidasu Dev"
GENERATE=1
if [[ "${1:-}" == "--skip-generate" ]]; then
  GENERATE=0
fi

# 1. Toolchain check. Only xcodegen is fatal here; the others gate later
#    build scripts, which point at their own install instructions.
if ! command -v xcodegen >/dev/null 2>&1; then
  echo "ERROR: xcodegen not found (brew install xcodegen)" >&2
  exit 1
fi
for tool in cmake ninja cargo; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "WARNING: ${tool} not found — needed by scripts/build_runtime.sh / build_tokenizer.sh" >&2
  fi
done

# 2. Resolve the signing identity.
identity="${MIMIDASU_SIGN_IDENTITY:-}"
if [[ -n "${identity}" ]]; then
  echo "==> Using MIMIDASU_SIGN_IDENTITY (${identity})"
elif security find-identity -v -p codesigning 2>/dev/null | grep -qF "\"${PREFERRED_IDENTITY}\""; then
  identity="${PREFERRED_IDENTITY}"
  echo "==> Found \"${PREFERRED_IDENTITY}\" certificate — Screen Recording grants persist across rebuilds"
elif security find-identity -v -p codesigning 2>/dev/null | grep -qF '"Mimidasu Dev"'; then
  identity="Mimidasu Dev"
  echo "==> Found legacy \"Mimidasu Dev\" certificate — Screen Recording grants persist across rebuilds"
else
  identity="-"
  echo "==> No \"${PREFERRED_IDENTITY}\" certificate found — falling back to ad-hoc signing"
  echo "    (create the certificate to keep Screen Recording grants stable across rebuilds;"
  echo "     with ad-hoc signing macOS re-asks for Screen Recording access after each rebuild)"
fi

# 3. Write the xcconfig the generated project reads its identity from.
mkdir -p "$(dirname "${XCCONFIG}")"
cat > "${XCCONFIG}" <<EOF
// Generated by scripts/bootstrap.sh — do not edit; re-run the script instead.
CODE_SIGN_IDENTITY = ${identity}
EOF

# 4. Generate the project.
if [[ "${GENERATE}" -eq 1 ]]; then
  echo "==> Generating Xcode project"
  (cd "${REPO_ROOT}" && xcodegen generate)
fi

echo
echo "Done. Signed with: ${identity}  (${XCCONFIG})"
if [[ "${GENERATE}" -eq 1 ]]; then
  echo "Open Mimidasu.xcodeproj and run the \"Mimidasu\" scheme (⌘R)."
fi
